public class Publicclass {
    public static void nombreMetodo(){
        //Este metodo es vacio y no recibe ningun valor
    }
    
    public static String retornaTexto(){
        //Este metodo retorna un valor string
        return 'hola';
    }
    
    public static string retornaTextoRecibido(string parametroTexto){
        //Recibe un string y retorna el mismo string recibido
        return parametroTexto;
    }
}